#!/bin/csh

# define enviromental variables for running root
# you shoul execute
# 	source ./RootLogin
# before compilation!

############ For Root
###### version 1.01
setenv ROOTSYS    ~/lib/root
setenv LIBPATH ${ROOTSYS}/lib:/lib:/usr/lib:./
