COMMAND = 
COMMAND_OBJECTS = 
LOCAL_LIB   =  2brems.a 
LIB_OBJECTS =  \
	cellar.o interbrem.o \
##############   What has to be built
all:	$(LOCAL_LIB) 
###############
FFLAGS = <FFLAGS>
F77 = f77
AR = ar
RANLIB = ranlib
LD = $(F77)
#############
interbrem.f:		GPS.h
#############
.f.o:
	$(F77) $(FFLAGS) -c $<
$(LOCAL_LIB): $(LIB_OBJECTS)
	$(AR) rv  $(LOCAL_LIB) $(LIB_OBJECTS)
	$(RANLIB) $(LOCAL_LIB)
clean:
	rm -f *.o; rm -f *.a; rm -f *~ *.a

