#-----------------------------------------------------------------------
#       Template for makefile in production directory <dset>
#       Combine to be implemented!!!
#       bjobs, bqueues
#-----------------------------------------------------------------------
MCMD=<main>
DSET=<dset>
CLASS=<class>
#-----------------------------------------------------------------------
#SRCLIST= "../ ../../yfslib ../../bornv ../../glibk ../../KK2f"
SRCLIST= "../"
#-----------------------------------------------------------------------
# Interactive:  run start stop and continue
#-----------------------------------------------------------------------
prepare:
	(ln -s ../../.KK2f_defaults ./.KK2f_defaults )
	(ln -s ../../dizet          ./dizet )
#-----------------------------------------------------------------------
start:
	(cp ../iniseed/iniseed.0 ./iniseed	;\
	 cp ../semaphore.start   ./semaphore	;\
	 cp ./$(DSET).input ./pro.input		;\
	 mv -f ./pro.output ./pro.output.bak	;\
	 mv -f ./rmain.root ./rmain.root.bak	;\
	 time ../${MCMD}			)&
#-----------------------------------------------------------------------
batch:
	(cp ../iniseed/iniseed.0 ./iniseed	;\
	 cp ../semaphore.start   ./semaphore	;\
	 cp ./$(DSET).input ./pro.input		;\
	 mv -f ./pro.output ./pro.output.bak	;\
	 mv -f ./rmain.root ./rmain.root.bak	;\
	 ../${MCMD} > ./stdout &	)
#-----------------------------------------------------------------------
stop:
	(cp ../semaphore.stop ./semaphore )&
#-----------------------------------------------------------------------
cont:
	(cp semaphore  semaphore.bak		;\
	 cp -f rmain.root   rmain.root.bak	;\
	 mv -f pro.output pro.output.bak	;\
	 time ../${MCMD}			)&
#-----------------------------------------------------------------------
start-debug:
	(cp ../iniseed/iniseed.0 ./iniseed	;\
	 cp ../semaphore.start   ./semaphore	;\
	 cp ./$(DSET).input ./pro.input		;\
	 mv -f ./pro.output ./pro.output.bak	;\
	 mv -f ./rmain.root ./rmain.root.bak	;\
	 xldb -I  ${SRCLIST} ../${MCMD}	)&
#-----------------------------------------------------------------------
cont-debug:
	(cp semaphore  semaphore.bak		;\
	 cp -f rmain.root   rmain.root.bak	;\
	 mv -f pro.output pro.output.bak	;\
         ddd --directory="../" ../${MCMD}	)
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
#   Batch on farm:  initialize, submit and stop
#-----------------------------------------------------------------------
farm6-LSF:
	(csh ../farm-init "1 2 3 4 5 6" \
	${MAIN} ${DSET} LSF ${CLASS} )
farm12-LSF:
	(csh ../farm-init "1 2 3 4 5 6 7 8 9 10 11 12" \
	${MAIN} ${DSET} LSF ${CLASS} )
farm24-LSF:
	(csh ../farm-init "1 2 3 4 5 6 7 8 9 10 11 12 \
	      13 14 15 16 17 18 19 20 21 22 23 24 " \
	${MAIN} ${DSET} LSF ${CLASS} )
#-----------------------------------------------------------------------
farm-gtar:
	(gtar -cvzf ../../../${DSET}-farm.tar.gz farm)
#-----------------------------------------------------------------------
bsubmit6:
	(csh ../farm-bsubmit ${DSET} ${CLASS} "1 2 3 4 5 6")
bsubmit12:
	(csh ../farm-bsubmit ${DSET} ${CLASS} "1 2 3 4 5 6 7 8 9 10 11 12")
bsubmit18:
	(csh ../farm-bsubmit ${DSET} ${CLASS} "1 2 3 4 5 6 7 8 9 10 11 12 \
	                13 14 15 16 17 18")
bsubmit24:
	(csh ../farm-bsubmit ${DSET} ${CLASS} "1 2 3 4 5 6 7 8 9 10 11 12 \
	                13 14 15 16 17 18 19 20 21 22 23 24 ")
bsubmit:
	(csh foreach i (farm/*/) echo $i end)
#-----------------------------------------------------------------------
stop1:
	(csh ../farm-stop   ${DSET} "1")
stop6:
	(csh ../farm-stop   ${DSET} "1 2 3 4 5 6 ")
stop12:
	(csh ../farm-stop   ${DSET} "1 2 3 4 5 6 7 8 9 10 11 12")
stop18:
	(csh ../farm-stop   ${DSET} "1 2 3 4 5 6 7 8 9 10 11 12 \
	                13 14 15 16 17 18 ")
stop24:
	(csh ../farm-stop   ${DSET} "1 2 3 4 5 6 7 8 9 10 11 12 \
	                13 14 15 16 17 18 19 20 21 22 23 24 ")
#-----------------------------------------------------------------------
run1:
	(cd ./farm/1/; ${DSET}.cmd.1)&
#--------- cobmine (add) results from several subdirectories -----------
combine2:
	(hadd ./rmain.root ./farm/1/rmain.root ./farm/2/rmain.root)
combine:
	(hadd ./rmain.root farm/*/*.root)
#-----------------------------------------------------------------------
#---- query
q-semaphore:
	(ls -altr farm/*/semaphore)
q-nev:
	(cat farm/*/semaphore | grep nev)
q-cont:
	(cat farm/*/semaphore | grep cont)
#-----------------------------------------------------------------------
clean:                                                     
	(rm -f *.o *.a *~ *.exe core *.err *.out)
CLEAN:  clean
	(rm  -R -f farm )
#-----------------------------------------------------------------------
