      subroutine iniofc
      return
      end

      FUNCTION SIGEE_WRAP(Q2,JNP)  
      SIGEE_WRAP=0
      RETURN
      END


      SUBROUTINE DAM1PI_wrap(INUM,PNU,AMF0,PKK,AMF1,GAMM,HV)
      REAL  PKK(4),PNU(4),HV(4)
      RETURN
      END

      FUNCTION FCONST_wrap(INUM)
      FCONST_WRAP=1
      RETURN
      END

      SUBROUTINE CURR2_wrap(MNUM,PIM1,PIM2,HADCUR)
      REAL  HV(4),PT(4),PN(4),PIM1(4),PIM2(4)
      COMPLEX HADCUR(4)
      RETURN
      END

      SUBROUTINE DAM2PI_wrap(MNUM,PT,PN,PIM1,PIM2,AMPLIT,HV)
      REAL  HV(4),PT(4),PN(4),PIM1(4),PIM2(4)
      RETURN
      END

      SUBROUTINE CURR3PI_wrap(MNUM,PIM1,PIM2,PIM3,HADCUR)
      REAL  HV(4),PT(4),PN(4),PIM1(4),PIM2(4),PIM3(4)
      COMPLEX HADCUR(4)
      RETURN
      END

      SUBROUTINE DAM3PI_wrap(MNUM,PT,PN,PIM1,PIM2,PIM3,AMPLIT,HV)
      REAL  HV(4),PT(4),PN(4),PIM1(4),PIM2(4),PIM3(4)
      RETURN
      END

      SUBROUTINE CURR4_wrap(MNUM,PIM1,PIM2,PIM3,PIM4,HADCUR)
      REAL  HV(4),PT(4),PN(4),PIM1(4),PIM2(4),PIM3(4),PIM4(4)
      COMPLEX HADCUR(4)
      RETURN
      END

      SUBROUTINE DAM4PI_wrap(MNUM,PT,PN,PIM1,PIM2,PIM3,PIM4,AMPLIT,HV)
      REAL  HV(4),PT(4),PN(4),PIM1(4),PIM2(4),PIM3(4),PIM4(4)
      RETURN
      END




      SUBROUTINE CURR5_wrap(MNUM,PIM1,PIM2,PIM3,PIM4,PIM5,HADCUR)
      REAL  HV(4),PT(4),PN(4),PIM1(4),PIM2(4),PIM3(4),PIM4(4),PIM5(4)
      COMPLEX HADCUR(4)
      RETURN
      END

      SUBROUTINE DAM5PI_wrap(MNUM,PT,PN,PIM1,PIM2,PIM3,PIM4,PIM5,AMPLIT,HV)
      REAL  HV(4),PT(4),PN(4),PIM1(4),PIM2(4),PIM3(4),PIM4(4),PIM5(4)
      RETURN
      END

      SUBROUTINE DAMPRY_wrap(ITDKRC,XK0DEC,XK,XA,QP,XN,AMPLIT,HV)
      IMPLICIT REAL*8 (A-H,O-Z)
      REAL*8  HV(4),QP(4),XN(4),XA(4),XK(4)
      RETURN
      END
